[project]
name = "oral-prep"
version = "0.1.0"
description = "An oral prep tool for pilots"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.4",
    "markdown>=3.8.2",
    "pillow>=11.3.0",
]
