# Generated by Django 5.2.4 on 2025-07-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[("PRIVATE", "Private"), ("COMMERCIAL", "Commercial")],
                        verbose_name="certificate type",
                    ),
                ),
                (
                    "plane_type",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("C152", "Cessna 152"),
                            ("C172", "Cessna 172"),
                            ("WARRIOR", "Piper Warrior"),
                            ("MOONEY", "Mooney M20J"),
                        ],
                        verbose_name="plane type",
                    ),
                ),
                ("question", models.TextField(verbose_name="question")),
                ("answer", models.TextField(verbose_name="answer")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="image"
                    ),
                ),
                (
                    "import_id",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="import ID"
                    ),
                ),
            ],
        ),
    ]
