# Generated by Django 5.2.4 on 2025-07-03 00:49

import json
from pathlib import Path
from django.core.files import File
from django.db import migrations


DATA_PATH = Path(__file__).resolve().parent.parent.parent.parent / "data"
QUESTIONS = DATA_PATH / "questions.json"
IMAGES = DATA_PATH / "images"


def load_data():
    with QUESTIONS.open() as f:
        return json.load(f)


def import_data(apps, _):
    Question = apps.get_model("quiz", "Question")

    for question in load_data():
        model = Question(
            certificate_type=question["certificate"],
            plane_type=question["type"],
            question=question["question"],
            answer=question["answer"],
            import_id=question["questionId"]
        )

        if question["imageFile"] is not None:
            path = IMAGES / question["imageFile"]
            with path.open("rb") as f:
                model.image = File(f, name=path.name)
                model.save()
        else:
            model.save()


def remove_data(apps, _):
    Question = apps.get_model("quiz", "Question")

    ids = {q["questionId"] for q in load_data()}

    Question.objects.filter(import_id__in=ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(import_data, remove_data)
    ]
