# Generated by Django 5.2.4 on 2025-07-11 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_preferences"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ("id",)},
        ),
    ]
