# Generated by Django 5.2.4 on 2025-07-04 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_import_questions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Preferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[("PRIVATE", "Private"), ("COMMERCIAL", "Commercial")],
                        default="PRIVATE",
                        verbose_name="certificate type",
                    ),
                ),
                (
                    "plane_type",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("C152", "Cessna 152"),
                            ("C172", "Cessna 172"),
                            ("WARRIOR", "Piper Warrior"),
                            ("MOONEY", "Mooney M20J"),
                        ],
                        default=None,
                        null=True,
                        verbose_name="plane type",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
